name: education_system
description: Education System

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: NeoSans
      fonts:
        - asset: assets/fonts/primary/Neo Sans Std Bold.otf
          weight: 600
        - asset: assets/fonts/primary/Neo Sans Std Medium.otf
          weight: 500
        - asset: assets/fonts/primary/Neo Sans Std Regular.otf
          weight: 400
        - asset: assets/fonts/primary/Neo Sans Std Black.otf


